---
# yaml-language-server: $schema=https://kubernetes.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-logs
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: opentoucan
  datasource:
    name: VictoriaLogs
    type: victoriametrics-logs-datasource
    uid: victorialogs
    access: proxy
    url: http://victoria-logs-server.observability.svc.cluster.local:9428
  plugins:
    - name: victoriametrics-logs-datasource
      version: latest
