---
# yaml-language-server: $schema=https://kubernetes.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dotbot-pr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dotbot-pr
    creationPolicy: Owner
    template:
      data:
        Discord__PublicKey: '{{ .DISCORD_PUBLIC_KEY }}'
        Discord__Token: '{{ .DISCORD_TOKEN }}'
        REDIS_PASSWORD: '{{ .REDIS_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
        VehicleEnquiry__ApiKey: '{{ .VES_API_KEY }}'
        MotHistory__ClientId: '{{ .MOT_CLIENT_ID }}'
        MotHistory__TenantId: '{{ .MOT_TENANT_ID }}'
        MotHistory__ClientSecret: '{{ .MOT_CLIENT_SECRET }}'
        MotHistory__ApiKey: '{{ .MOT_API_KEY }}'
  dataFrom:
    - extract:
        key: dotbot-pr
