---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-forgejo
spec:
  discoveryFilter: sillock/*
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_PLATFORM
      value: forgejo
    - name: RENOVATE_ENDPOINT
      value: https://codeberg.org/api/v1
    - name: RENOVATE_GIT_AUTHOR
      value: "Renovate <bot@sillock.com>"
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
  image: ghcr.io/renovatebot/renovate:42.1.3@sha256:724220885785c57898d5709624eceddb012d8f63ac08a8f718aa77c13ca621bc
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: "@hourly"
  secretRef: renovate-operator
