---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./l2.yaml
configMapGenerator:
  - name: cilium-helm-values
    files:
      - helm-values.yaml
generatorOptions:
  disableNameSuffixHash: true
