---
nameReference:
  - kind: PersistentVolumeClaim
    fieldSpecs:
      - kind: HelmRelease
        path: spec/values/persistence/data/existingClaim
  - kind: OCIRepository
    fieldSpecs:
      - kind: HelmRelease
        path: spec/chartRef/name
