---
# yaml-language-server: $schema=https://kubernetes.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dotbot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dotbot-secret
    creationPolicy: Owner
    template:
      data:
        RabbitMQ__User: '{{ .RABBITMQ_DEFAULT_USER }}'
        RabbitMQ__Password: '{{ .RABBITMQ_DEFAULT_PASS }}'
        Discord__PublicKey: '{{ .DISCORD_PUBLIC_KEY }}'
        Discord__Token: '{{ .DISCORD_TOKEN }}'
        ConnectionStrings__dotbot: '{{ .CONNECTION_STRING }}'
        ConnectionStrings__redis: 'dragonfly-instance.database.svc.cluster.local:6379,password={{ .REDIS_PASSWORD }}'
        S3__ServiceURL: '{{ .S3_URL }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
        VehicleEnquiry__ApiKey: '{{ .VES_API_KEY }}'
        MotHistory__ClientId: '{{ .MOT_CLIENT_ID }}'
        MotHistory__TenantId: '{{ .MOT_TENANT_ID }}'
        MotHistory__ClientSecret: '{{ .MOT_CLIENT_SECRET }}'
        MotHistory__ApiKey: '{{ .MOT_API_KEY }}'
  dataFrom:
    - extract:
        key: dotbot
    - extract:
        key: rabbitmq
---
# yaml-language-server: $schema=https://kubernetes.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dotbot-migrator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dotbot-migrator-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dotbot-migrator
