---
# yaml-language-server: $schema=https://kubernetes.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-opentoucan
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: flux-opentoucan
    creationPolicy: Owner
    template:
      data:
        username: "{{ .USERNAME }}"
        password: "{{ .PAT }}"
  dataFrom:
    - extract:
        key: opentoucan
