---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-opentoucan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-opentoucan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: flux-opentoucan
    namespace: opentoucan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dragonfly-instance
rules:
- apiGroups: ["dragonflydb.io"]
  resources: ["dragonflies"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dragonfly-instance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dragonfly-instance
subjects:
  - kind: ServiceAccount
    name: flux-opentoucan
    namespace: opentoucan
