---
# yaml-language-server: $schema=https://kubernetes.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-dragonfly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    template:
      data:
        REDIS_PASSWORD: '{{ .REDIS_PASSWORD }}'
  dataFrom:
    - extract:
        key: ${APP}
