---
nameReference:
  - kind: ExternalSecret
    fieldSpecs:
      - kind: Dragonfly
        path: spec/authentication/passwordFromSecret/name
  - kind: OCIRepository
    fieldSpecs:
      - kind: HelmRelease
        path: spec/chartRef/name
