---
# yaml-language-server: $schema=https://kubernetes.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app atlantis
spec:
  chart:
    spec:
      chart: atlantis
      version: 5.23.0
      sourceRef:
        kind: HelmRepository
        name: *app
  interval: 1h
  values:
    repoConfig: |
      ---
      repos:
        - id: /.*/
          allowed_workflows: [prod]
          apply_requirements: [undiverged]
          import_requirements: [undiverged]
          allowed_overrides:
            - workflow
            - delete_source_branch_on_merge
            - repo_locking
            - repo_locks
            - custom_policy_check
          delete_source_branch_on_merge: true
      workflows:
        prod:
          plan:
            steps:
              - init:
                  extra_args: ["-upgrade"]
              - plan:
                  extra_args: ["-var-file", "./env/prod.tfvars", "-var", "environment=prod"]
          apply:
            steps:
              - apply
          import:
            steps:
              - init:
                  extra_args: ["-upgrade"]
              - import:
                  extra_args: ["-var-file", "./env/prod.tfvars"]
          state_rm:
            steps:
              - init:
                  extra_args: ["-upgrade"]
              - state_rm:
                  extra_args: ["-lock=false"]
      metrics:
        prometheus:
          endpoint: /metrics
    defaultTFDistribution: opentofu
    vcsSecretName: atlantis-github-secret
    loadEnvFromSecrets:
      - atlantis-env-secret
    loadEnvFromConfigMaps:
      - atlantis-env
    orgAllowlist: github.com/opentoucan/*
    githubApp:
      id: "1110841"
      installationId: "59529854"
    service:
      type: ClusterIP
      port: 80
      targetPort: 4141
    servicemonitor:
      enabled: true
    ingress:
      enabled: false
    volumeClaim:
      enabled: true
      dataStorage: 10Gi
      storageClassName: "openebs-hostpath"
      accessModes: ["ReadWriteOnce"]
